import{a as v,S as q,i as n}from"./assets/vendor-DcHCnVjq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const P="55762105-53f0d60783cc05dbb5c3cf186",$=v.create({baseURL:"https://pixabay.com/api/"});async function d(t,r=1){const i={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await $.get("",{params:i})).data}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){const r=t.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:a,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${i}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b>${o}</p>
        <p class="info-item"><b>Views</b>${a}</p>
        <p class="info-item"><b>Comments</b>${w}</p>
        <p class="info-item"><b>Downloads</b>${S}</p>
      </div>
    </li>`).join("");u.insertAdjacentHTML("beforeend",r),M.refresh()}function E(){u.innerHTML=""}function p(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function y(){f.classList.remove("hidden")}function b(){f.classList.add("hidden")}const B=document.querySelector("#search-form"),R=document.querySelector(".load-more-btn");let l="",c=1;const L=15;B.addEventListener("submit",x);R.addEventListener("click",O);async function x(t){t.preventDefault();const r=t.currentTarget,i=r.elements.searchText.value.trim();if(i===""){n.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}l=i,c=1,E(),b(),p();try{const s=await d(l,c);if(s.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(s.hits),s.totalHits>L&&y()}catch(s){n.error({title:"Error",message:`Something went wrong: ${s.message}`,position:"topRight"})}finally{g(),r.reset()}}async function O(){c+=1,b(),p();try{const t=await d(l,c);h(t.hits),C();const r=Math.ceil(t.totalHits/L);c>=r?n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):y()}catch(t){n.error({title:"Error",message:`Failed to load more images: ${t.message}`,position:"topRight"})}finally{g()}}function C(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
